[package]
name = "lunabot-cu"
version = "0.1.0"
edition = "2021"
default-run = "lunabot"
build = "build.rs"


# The main executable of your application
[[bin]]
name = "lunabot"
path = "src/main.rs"

# A custom made log reader application for your application.
[[bin]]
name = "lunabot-logreader"
path = "src/logreader.rs"
required-features = ["logreader"]

[features]
default = []
logreader = ["dep:cu29-export"]

[dependencies]
cu29 = {  version = "0.8", features = ["log-level-debug"] }
bincode = { version = "2.0.1", features = ["derive", "serde"] }
cu29-helpers = { version = "0.8"  }
cu29-export = { version = "0.8" , optional = true }
# Add Copper official component crates for milestone 1
cu-apriltag = "0.8"
cu-consolemon = "0.8"
cu-sensor-payloads = "0.8"
cu-spatial-payloads = "0.8"
image = { version = "0.24", default-features = false, features = ["jpeg"] }
v4l = "0.14"
udev = "0.9"
crossbeam-channel = "0.5"
anyhow = "1"
serde = { version = "1", features = ["derive"] }

[build-dependencies]
ron = "0.8"
serde = { version = "1", features = ["derive"] }

