[package]
name = "lunabot-cu"
version = "0.1.0"
edition = "2021"
default-run = "lunabot"
build = "build.rs"


# The main executable of your application
[[bin]]
name = "lunabot"
path = "src/main.rs"

# A custom made log reader application for your application.
[[bin]]
name = "lunabot-logreader"
path = "src/logreader.rs"
required-features = ["logreader"]

[features]
default = []
logreader = ["dep:cu29-export"]

[dependencies]
cu29 = {  git = "https://github.com/matthewashton-k/copper-rs", features = ["log-level-debug"] }
bincode = { version = "2.0.1", features = ["derive", "serde"] }
cu29-helpers = { git = "https://github.com/matthewashton-k/copper-rs" }
cu29-export = { git = "https://github.com/matthewashton-k/copper-rs" , optional = true }
# Add Copper official component crates for milestone 1
cu-apriltag = { git = "https://github.com/matthewashton-k/copper-rs" }
cu-consolemon = { git = "https://github.com/matthewashton-k/copper-rs" }
cu-sensor-payloads = { git = "https://github.com/matthewashton-k/copper-rs" }
cu-spatial-payloads = { git = "https://github.com/matthewashton-k/copper-rs" }
image = { version = "0.24", default-features = false, features = ["jpeg"] }
v4l = "0.14"
udev = "0.9"
crossbeam-channel = "0.5"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
cu-v4l = { git = "https://github.com/matthewashton-k/copper-rs" }
libc = "0.2.173"
nix = "0.30.1"

[build-dependencies]
ron = "0.8"
serde = { version = "1", features = ["derive"] }

