[package]
name = "lunabot-cu"
version = "0.1.0"
edition = "2021"
default-run = "lunabot"
build = "build.rs"


# The main executable of your application
[[bin]]
name = "lunabot"
path = "src/main.rs"

# A custom made log reader application for your application.
[[bin]]
name = "lunabot-logreader"
path = "src/logreader.rs"
required-features = ["logreader"]

[features]
default = []
logreader = ["dep:cu29-export"]

[dependencies]
cu29 = {  path = "../copper-rs/core/cu29", features = ["log-level-info", "log-level-error"] }
bincode = { version = "2.0.1", features = ["derive", "serde"] }
cu29-helpers = { path = "../copper-rs/core/cu29_helpers" }
cu29-export = { path = "../copper-rs/core/cu29_export" , optional = true }
# Add Copper official component crates for milestone 1
cu-apriltag = { path = "../copper-rs/components/tasks/cu_apriltag" }
cu-consolemon = { path = "../copper-rs/components/monitors/cu_consolemon" }
cu-sensor-payloads = { path = "../copper-rs/components/payloads/cu_sensor_payloads" }
cu-spatial-payloads = { path = "../copper-rs/components/payloads/cu_spatial_payloads" }
image = { version = "0.24", default-features = false, features = ["jpeg"] }
v4l = "0.14"
udev = "0.9"
crossbeam-channel = "0.5"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
cu-v4l = { path = "../copper-rs/components/sources/cu_v4l" }
libc = "0.2.173"
nix = "0.30.1"
cu29-runtime = { path = "../copper-rs/core/cu29_runtime", features = ["jemalloc"] }

nalgebra = { version = "0.32", features = [
    "serde-serialize",
    "convert-bytemuck",
] }

[build-dependencies]
ron = "0.8"
serde = { version = "1", features = ["derive"] }

